// =========================================================================
// AccountTrigger
// Auto-generated by flow-to-apex POC.
// Original Flow target object: Account
// =========================================================================
trigger AccountTrigger on Account (after insert, after update) {
    AccountCountContactsHandler.afterSave(Trigger.new, Trigger.oldMap);
}
