// =========================================================================
// AccountTrigger
// Auto-generated by flow-to-apex POC.
// Original Flow target object: Account
// =========================================================================
trigger AccountTrigger on Account (before insert) {
    AccountSetDefaultIndustryHandler.beforeSave(Trigger.new);
}
