// =========================================================================
// AccountTrigger
// Auto-generated by flow-to-apex POC.
// Original Flow target object: Account
// =========================================================================
trigger AccountTrigger on Account (after update) {
    AccountCloseOpenOpportunitiesHandler.afterSave(Trigger.new, Trigger.oldMap);
}
